singleQuote: true
semi: false
printWidth: 120
trailingComma: none
vueIndentScriptAndStyle: false
singleAttributePerLine: false
htmlWhitespaceSensitivity: 'ignore'
bracketSameLine: true
endOfLine: 'auto'
arrowParens: 'avoid'
